config/routes.rb
FeedThePet::Application.routes.draw do
  devise_for :owners

  resources :owners
  get ":owner_id/pets/new" => "pets#new", :as => :new_pet
  resources :pets do
    post "feed/:energy" => "pets#feed" , :as => :feed
  end

  root to: "owners#show"

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :age, :name
  has_many :pets

  validates_presence_of :email
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  attr_accessible :health, :name, :picture
  belongs_to :owner

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_owner!

  def after_sign_in_path_for(resource)
    owner_path(resource)
  end

  def after_sign_out_path_for(resource)
    new_owner_session_path
  end
end

app/controllers/owners_controller.rb
class OwnersController < InheritedResources::Base

  def show
    @owner = current_owner
    @pets = @owner.pets
  end
end

app/controllers/pets_controller.rb
class PetsController < InheritedResources::Base
  def index
    @owner = Owner.find(params[:owner_id])
    @pets = @owner.pets
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @owner = Owner.find(params[:owner_id])
    @pet = @owner.pets.build
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    @owner = Owner.find(params[:owner_id])
    @pet = @owner.pets.build(:name => params[:pet][:name], :picture => params[:pet][:picture])
    @pet.health = 50

      if @pet.save
         redirect_to @owner, notice: 'Pet was successfully created.'
      else
        render action: "new"
      end
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update_attributes(params[:pet])
       redirect_to @pet, notice: 'Pet was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to owner_path(current_owner)
  end

  def feed
    energy = params[:energy].to_i
    @pet = Pet.find(params[:pet_id])
    @pet.health += energy
    @pet.save!
    redirect_to owner_path(current_owner)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Feed The Pet</title>
  <meta name="description" content="Feed Me" />
  <meta name="author" content="Tushar Sonawane">
  <meta name="viewport" content="width=device-width">


  <%= stylesheet_link_tag "style", :media => "all" %>
  <style type="text/css">
      #logo-big {
          display: block;
          background: url(<%= asset_path 'logo-big.png' %>) no-repeat;
          width: 500px;
          height: 100px;
          text-indent: -9999px;
      }

      #logo-small {
          display: block;
          background: url(<%= asset_path 'logo-big.png' %>) no-repeat;
          width: 250px;
          height: 50px;
          text-indent: -9999px;
      }
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="grid grid-pad">
  <header class="logo">
    <a href="#" id="logo-big">Feed Me!!</a>
  </header>

<%= yield %>
</div>

</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <!--
  <%=owner_signed_in? %>
  <%=current_owner %>
  -->
  <% @owners.each do |owner| %>
  <tr>
    <td><%= owner.email %></td>
    <td><%= link_to 'Show', owner %></td>
    <!--<td><%= link_to 'Edit', edit_owner_path(owner) %></td>
    <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p>
    <b>Welcome,
        <%= @owner.email %>
    </b>
    <%= link_to '(Logout)', destroy_owner_session_path %>
    <%= link_to 'New Pet', new_pet_path(:owner_id => @owner.id), :class => 'bttn' %>

</p>

<% pets = @pets.all %>
<% if pets.empty? %>
    <em>you dont own any pet yet?</em>
<% else %>
<% pets.each do |pet| %>
<div class="grid grid-pad">
<div class="col-1-2">
  <div class="content">
    <section id="petty">
      <figure>
        <%= image_tag(pet.picture_url, :width => 240, :id => 'photo') %>
      </figure>
    </section>
    <section id="health-meter">
      <progress value="<%= pet.health %>" max="100"></progress>
      <span>Health ( <%= pet.health %>% )</span>
    </section>
  </div>
</div>
<div class="col-1-2">
  <div class="content">
    <section id="info">
      <h2 class="pet-name"><%= pet.name %></h2>
    </section>
    <nav>
      <ul>
        <li id="food1">
          <%= link_to 'Food1', pet_feed_path(:pet_id => pet.id, :energy => 5), :method => :post %>
        </li>

        <li id="food2">
          <%= link_to 'Food2', pet_feed_path(:pet_id => pet.id, :energy => 10), :method => :post %>
        </li>

        <li id="set-free">
          <%= link_to 'Set Free', pet, :method => :delete %>
        </li>
      </ul>
    </nav>
  </div>
</div>
</div>
<% end %>
<% end %>
<!--
<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>
-->

<script type="text/javascript">
    $(function() {
        var health = $('#health-meter').find('progress').val();
        $('#food1').find('a').click(function() {
            if(health + 5 >= 100) {
                alert("I'm not hungry anymore! Set me free!!!");
                return false;
            }
        });

        $('#food2').find('a').click(function() {
            if(health + 10 >= 100) {
                alert("I'm not hungry anymore! Set me free!!!");
                return false;
            }
        });
    })();
</script>

app/views/pets/_form.html.erb
<%= p @owner.name%>
<%= form_for(@pet, :url => pets_path(:owner_id => @owner.id)) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Health</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pets.each do |pet| %>
  <tr>
    <td><%= pet.name %></td>
    <td><%= pet.health %></td>
    <td><%= link_to 'New', new_pet_path %></td>
    <td><%= link_to 'Show', pet %></td>
    <td><%= link_to 'Feed', feed_pets_path(:id => pet.id, :energy => 5), :method => :post %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', owner_path(@pet.owner), :class => 'bttn' %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pet.name %>
</p>

<p>
  <b>Health:</b>
  <%= @pet.health %>
</p>

<%= link_to 'Back', owner_path(@pet.owner) %>